model_list:
  - model_name: db-openai-endpoint
    litellm_params:
      model: openai/gpt-5
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/
  - model_name: db-openai-endpoint
    litellm_params:
      model: openai/gpt-5
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/

litellm_settings:
  callbacks: ["prometheus", "otel"]
  service_callback: ["prometheus_system"]


